import Head from 'next/head'
import { useSession, signOut } from "next-auth/react";
import Navbar from '../components/Navbar';
import Layout from '../components/Layout';
import Homepage from '../components/Homepage';
import { getCsrfToken } from "next-auth/react";
import Dashboard from '../components/Dashboard';

export default function Home({csrfToken}) {

  const { data: session } = useSession()

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar session={session} signOut={signOut} />

      {!session ? (
        <>
          <Homepage session={session} csrfToken={csrfToken} />
        </>
      ) : (
        <>
          <Dashboard session={session}/>
        </>
      )}


      
    </Layout>
  )
}

export async function getServerSideProps(context) {
  const csrfToken = await getCsrfToken(context);
  return {
    props: {
      csrfToken,
    },
  };
}
